using System.Runtime.CompilerServices;
using Student_Tracker_Blazor;

namespace Student_Tracker_Blazor
{
    public class Login
    {
        public void LoginThing()
        {
            Console.WriteLine("Hello World! Imma make a student, an admin, and a professor!");
            Student student = new Student();
            student.FirstName = "Sarah";
            student.LastName = "Bigbrain";
            student.ENumber = "E1";
            student.Emailaddr = "thingy@email.com.gov";
            student.Password = "123";

            Admin admin = new Admin();
            admin.FirstName = "Bobby Bigbrain";
            admin.Emailaddr = "useless@email.net.dev";
            admin.Password = "456";

            Professor professor = new Professor();
            professor.FirstName = "Tiara Bigbrain";
            professor.Emailaddr = "pointless@email.gov.thing";
            professor.Password = "789";

            Console.WriteLine($"Here is the student!\nName: {student.FirstName}\nEnumber: {student.ENumber}\nEmail: {student.Emailaddr}\nPassword: {student.Password}\n");
            Console.WriteLine($"Here is the admin!\nName: {admin.FirstName}\nEmail: {admin.Emailaddr}\nPassword: {admin.Password}\n");
            Console.WriteLine($"Here is the professor!\nName: {professor.FirstName}\nEmail: {professor.Emailaddr}\nPassword: {professor.Password}\n");
        }

        public void UploadAdmin(Admin admin)
        {
            /*
             * This is a method to upload admins to the database. 
             * This is primarily supposed to be called when creating a user.
             * This can also be called when trying to change another user type to an Admin
             * The format in this method will match the ERD (Entity Relation Diagram) that Software Engineer Aurora Liles made.
            */

            string email = admin.Emailaddr;
            string password = admin.Password;               //This is a string-ified hash, right now. TODO: Make an integer later.
            Role role = admin.Role;
            string createdAt = admin.CreatedAt.ToString();
            string updatedAt = admin.UpdatedAt.ToString();
            string fistName = admin.FirstName;
            string firstEmail = admin.Emailaddr;

            /*
             * The UserID and the AdminID are generated by the database itself.
             * This does not need to be uploaded.
             */
        }

        public void UploadProfessor(Professor professor)
        {
            /*
             * This is a method to upload professors to the database. 
             * This is primarily supposed to be called when creating a user.
             * This can also be called when trying to change another user type to a Professor
             * The format in this method will match the ERD (Entity Relation Diagram) that Software Engineer Aurora Liles made.
            */

            string email = professor.Emailaddr;
            string password = professor.Password;               //This is a string-ified hash, right now. TODO: Make an integer later.
            Role role = professor.Role;
            string createdAt = professor.CreatedAt.ToString();
            string updatedAt = professor.UpdatedAt.ToString();
            string fistName = professor.FirstName;
            string firstEmail = professor.Emailaddr;

            /*
             * The UserID and the ProfessorID are generated by the database itself.
             * This does not need to be uploaded.
             */
        }
        public void UploadStudent(Student student)
        {
            /*
             * This is a method to upload students to the database. 
             * This is primarily supposed to be called when creating a user.
             * This can also be called when trying to change another user type to a Student
             * The format in this method will match the ERD (Entity Relation Diagram) that Software Engineer Aurora Liles made.
            */

            string eamiladdr = student.Emailaddr;
            string password = student.Password;               //This is a string-ified hash, right now. TODO: Make an integer later.
            Role role = student.Role;
            string createdAt = student.CreatedAt.ToString();
            string updatedAt = student.UpdatedAt.ToString();
            string fistName = student.FirstName;
            string firstEmail = student.Emailaddr;
            string professorID = student.ProfessorID;
            string enumber = student.ENumber;

            /*
             * The UserID and the StudentID are generated by the database itself.
             * This does not need to be uploaded.
             */
        }
    }
}
